<div class="copyright" style="font-size: xx-small; font-weight: lighter; color: gray;">
<br />
Powered by <a href="https://github.com/javabean/iNotes-exporter" target="_new">iNotes exporter</a> &copy; 2012&ndash;2014 C&eacute;drik LIME
</div>

</div><%--<div class="container"> --%>

<script src="//code.jquery.com/jquery.js"></script>
<%--script src="webjars/jquery/1.10.2/jquery.min.js"></script--%>
<script type="text/javascript" src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
<%--script type="text/javascript" src="webjars/bootstrap/2.3.2/js/bootstrap.min.js"></script--%>
<script type="text/javascript" src="js.js"></script>
