	<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
	<meta http-equiv="pragma" content="no-cache" /><!-- HTTP 1.0 -->
	<meta http-equiv="cache-control" content="no-cache,must-revalidate" /><!-- HTTP 1.1 -->
	<meta http-equiv="expires" content="0" /><!-- 0 is an invalid value and should be treated as 'now' -->
	<meta http-equiv="content-language" content="<%= response.getLocale() %>" />
	<meta name="author" content="Cedrik LIME" />
	<meta name="copyright" content="copyright 2013-2014 Cedrik LIME" />
	<meta name="robots" content="noindex,nofollow,noarchive" />
	<meta name="format-detection" content="telephone=no" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link rel="stylesheet" media="screen, projection" type="text/css" href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" />
	<%--link rel="stylesheet" media="screen, projection" type="text/css" href="webjars/bootstrap/2.3.2/css/bootstrap-combined.min.css" /--%>
